### ISSUE TITLE
Update Application Insights to 2.1.2

### ISSUE THREAD

**Issue by dhaval24** [VSChina/azure-dependencies-bom#11]
I see that application insights version 2.0.1 is being used here and azure-spring-boot-bom uses application insight version 2.1.2. This potentially causes conflict. 

Could you please update the version here to 2.1.2 and also remove dependency from azure-spring-boot-bom as this will be automatically pulled. Also I suggest that the priority of highest version should take place when dependency resolution happens.

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
There is no conflict here. We build this pom focus on how to resolve the dependencies from azure sdk.
Azure-spring-boot will depends on azure-dependencies, the properties there will be removed in next release.

**Comment by dhaval24** [comment]
That makes sense. For now when I pull the latest master of azure-spring-boot I get conflicting dependencies :) any suggestions on that?

**Comment by dhaval24** [comment]
also why is this repo not under microsoft github but instead under VSChina? Any specific reason for that?

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
Cloud you please help to show me how to reproduce the conflict ?
Like which versions reference in different location result in that conflict.
From my option, as import azure-dependencies-bom as dependencymanagement in azure-boot-bom, there should be only one reference to ai. How could only one reference result in conflict ?

**Comment by dhaval24** [comment]
@Incarnation-p-lee My point is about your current azure-spring-boot-bom file. It still has the dependencies which are mentioned in this azure-dependendencies-bom file. That's why I can see two versions of AI libraries on my class path when I run mvn depnedency:tree in the azure-spring-boot project

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
NO, I am not sure we are talking about the same repo in thread. The azure boot DO NOT reference to ai version property. Cloud u please try some ide or just grep the property there ? As I mentioned in below, the property is unused for now and will be removed in next release. You can see the dependency because the sample referenced to last release. Again, it will be disappear in next release.

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
I do mean the current master banch of azure-spring-boot. Let me guess how you check this, mvn claen package && mvn dependency:tree, right?This will build sample code, and you can see two version there because the sample code will use last release bom which do not involve the dependency bom. Have you really take a look into the code? Talk is cheap, show me the code.

**Comment by dhaval24** [comment]
@Incarnation-p-lee let's not make this a heated conversation, calm down :) I am just trying to better understand your repository structure, and totally agreeing that I might be wrong. That's why I am seeking clarification. Don't have any personal touches on this.

Now coming to the point . The current master of the `azure-spring-boot` project has this file:
https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot-bom/pom.xml

Take a look at this line:
https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot-bom/pom.xml#L56

It mentions the ai sdk version property to have 2.1.2. Now yes, I do see and agree with you that this property is unused in the dependencies in the pom. It's just dangling property as you said lying around which should be cleaned up I think. 

Currently 2.01. is then pulled from from azure-dependencies-bom I believe., 

Now when I am trying to contribute the micrometer registry for azuremonitor it uses 2.1.2 version of AI SDK and pulls it down. somehow maven is not able to resolve the version conflict after this. Therefore I see 2 AI SDK versions. 

I used mvn clean package and mvn dependency:tree to check for conflicts. Just FYI, I also purged local .m2 once to avoid any conflicts.

Hope this clarifies where I am stuck and you can help.

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
We next release will make the dependeces of azure all from the azure-dependency-bom. If no more questions about the issue, I will close it right now and infor you when the release is ready.

**Comment by dhaval24** [comment]
@Incarnation-p-lee sure you can close this issue. Thanks for understanding.

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
Thanks for your time and patient, good day!
