### ISSUE TITLE
Update azure-storage-blob to latest 10.x version

### ISSUE THREAD

**Issue by fduser1** [VSChina/azure-dependencies-bom#46]
Currently the azure-storage-blob version used in this project's bom is [10.1.0](https://github.com/VSChina/azure-dependencies-bom/blob/master/pom.xml#L52).

There have been bug fixes since that release. Latest azure-storage-blob 10.x version is [10.5.0](https://github.com/Azure/azure-storage-java/releases/tag/v10.5.0).  Please consider upgrading azure-storage-blob to the latest compatible version.

**Comment by Incarnation-p-lee** [comment]
@fduser1 
Thanks a lot. Could you help to file one PR for this ?

**Comment by fduser1** [comment]
@Incarnation-p-lee 
Completed your requested PR #47... please review. Thx!

**Comment by Incarnation-p-lee** [comment]
@fduser1  Thanks a lot. Merged already!
