### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by blacelle** [VSChina/azure-dependencies-bom#59]
I consider relying on this BOM. However, it relies on many very old versions even if the latest tag is around 1 year old:

https://mvnrepository.com/artifact/com.microsoft.azure/azure-dependencies-bom/2.3.0

e.g. azuez-identity and msal4j depenendecies are quite outdated.

**Comment by blacelle** [comment]
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-sdk-bom seems a fresher alternative

**Comment by chenrujun** [comment]
@blacelle 

Yes, please use azure-sdk-for-java repo.

And if you are using spring-boot or spring-cloud, you can use related bom, too.

Refs:
1. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-spring-boot-bom
2. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-spring-cloud-dependencies

**Comment by saragluna** [comment]
Closing this issue now.
